CREATE DATABASE mercado;

CREATE TABLE PRODUTO (COD_PROD INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, TIPO_PROD VARCHAR(50) NOT NULL, NOME_PROD VARCHAR(50) NOT NULL, PRECO_PROD DECIMAL(10,2) NOT NULL, QTD_PROD INT(100) NOT NULL);

CREATE TABLE TIPO_PRODUTO (ID_TIPO_PROD INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, NOME_PROD VARCHAR(50) NOT NULL);

CREATE TABLE CARRINHO (COD_CARRINHO INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, DATA_CARRINHO DATE() NOT NULL, COD_PRODFK REFERENCES PRODUTO(COD_PROD));